<?php
// $Id:

/**
 * @file
 * Used to automagically log out a user after a preset time.
 */

/**
 * Implementation of hook_perm().
 */
function js_logout_perm() {
  return array('administer js_logout');
}

/**
 * Implementation of hook_menu().
 */
function js_logout_menu() {
  $items = array();

  $items['admin/settings/js_logout'] = array(
    'title' => 'JS Logout',
    'description' => 'Administer JS Logout settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('js_logout_settings'),
    'access arguments' => array('administer js_logout'),
    'file' => 'js_logout.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['js_logout_ahah_logout'] = array(
    'title' => 'JS Logout',
    'page callback' => 'js_logout_ahah_logout',
    'access callack' => 'js_logout_access',
    'access arguments' => array(),
    'type' => MENU_CALLBACK
  );
  $items['js_logout_ahah_set_last'] = array(
    'title' => 'JS Logout AHAH Set Last',
    'page callback' => 'js_logout_ahah_set_last',
    'access callack' => 'js_logout_access',
    'access arguments' => array(),
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

/**
 * Access callback for js_logout.
 */
function js_logout_access() {
  global $user;
  $ret = FALSE;
  if ($user->uid && user_access('access content') && $_SERVER['REQUEST_METHOD'] != 'GET') {
    $ret = TRUE;
  }

  return $ret;
}

/**
 * Implementation of hook_help().
 */
function js_logout_help($path, $arg) {
  switch ($path) {
    case 'admin/help#js_logout':
      return '<p>'. t('This module allows you to force site users to be logged out after a given amount of time due to inactivity after first being presented with a confirmation dialog.') .'</p>';
  }
}

/**
 * Implementation of hook_init().
 */
function js_logout_init() {
  global $user;
  if ($user->uid) {
    $now = time();
    $timeout = variable_get('js_logout_timeout', 1800);
    $redirct_url = variable_get('js_logout_redirect_url', 'user/login');
    
    // return the timeout value as a setting and load js file
    $msg = t('@msg', array('@msg' => variable_get('js_logout_message', 'Your session is about to expire. Do you want to reset it?')));
    $settings = array(
      'timeout' => $timeout * 1000,
      'message' => t('@msg', array('@msg' => variable_get('js_logout_message', 'Your session is about to expire. Do you want to reset it?'))),
      'redirect_url' => url($redirct_url, array('query' => drupal_get_destination()))
    );
    drupal_add_js(array('js_logout' => $settings), 'setting');
    drupal_add_js(drupal_get_path('module', 'js_logout') . '/js_logout.js');

    // we need a backup plan if JS is disabled
    if (isset($_SESSION['js_logout_last'])) {
      if (($now - $_SESSION['js_logout_last']) >= $timeout) {
        _js_logoutlogout();
        drupal_goto($redirct_url, drupal_get_destination());
      }
      else {
        $_SESSION['js_logout_last'] = $now;
      }
    }
    else {
      $_SESSION['js_logout_last'] = $now;
    }
  }
}

/**
 * Callback that performs the actual logout and redirects the user.
 */
function js_logout_ahah_logout() {
  _js_logoutlogout();
  exit();
}

function js_logout_ahah_set_last() {
  $_SESSION['js_logout_last'] = time();
}

function _js_logoutlogout() {
  global $user;
  watchdog('user', 'Session automatically closed for %name by js_logout.', array('%name' => $user->name));

  // Destroy the current session:
  session_destroy();
  
  // Only variables can be passed by reference workaround.
  $null = NULL;
  user_module_invoke('logout', $null, $user);

  // Load the anonymous user
  $user = drupal_anonymous_user();
  
  // @todo: this message is not being displayed once logged out
  drupal_set_message(t('You have been logged out due to inactivity.'));
}